# Generated by Django 4.2.7 on 2026-08-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contractor',
            managers=[
            ],
        ),
    ]
