# Generated by Django 4.2.7 on 2026-08-31 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_contractor_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +375291234567 (коды: 29, 33, 44, 25)', regex='^\\+375(29|33|44|25)\\d{7}$')], verbose_name='Номер телефона'),
        ),
    ]
