# Generated by Django 4.2.7 on 2026-08-31 11:45

import access_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_alter_contractor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=access_control.models.upload_to_photo, verbose_name='Фото'),
        ),
    ]
