# Generated by Django 4.2.7 on 2026-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_alter_contractor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='access_code_entered',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Введенный код'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_method',
            field=models.CharField(choices=[('qr', 'QR-код'), ('code', 'Ручной ввод кода')], default='qr', max_length=20, verbose_name='Способ доступа'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='access_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Код доступа (4 цифры)'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='qr_code_scanned',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR код'),
        ),
    ]
