# Generated by Django 4.2.7 on 2026-09-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_accesslog_access_code_entered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='contractor',
            name='role',
            field=models.CharField(choices=[('contractor', 'Подрядчик'), ('guard', 'Охранник'), ('admin', 'Администратор')], default='contractor', max_length=20, verbose_name='Роль'),
        ),
    ]
