# Generated by Django 4.2.7 on 2026-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_alter_contractor_options_contractor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[('entry', 'Въезд'), ('exit', 'Выезд')], default='entry', max_length=10, verbose_name='Тип доступа'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='organization',
            field=models.CharField(default='', max_length=200, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
