# Generated by Django 4.2.7 on 2026-09-02 11:10

import access_control.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_accesslog_access_type_contractor_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslist',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Действителен с'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='valid_until',
            field=models.DateField(default=access_control.models.default_valid_until, verbose_name='Действителен до'),
        ),
    ]
