# Generated by Django 4.2.7 on 2026-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_accesslist_valid_from_accesslist_valid_until'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['contractor', 'is_successful'], name='access_cont_contrac_2edd67_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['scanned_at'], name='access_cont_scanned_3ba95d_idx'),
        ),
    ]
