# Generated by Django 4.2.7 on 2026-09-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_accesslog_access_cont_contrac_2edd67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslist',
            name='is_on_territory',
            field=models.BooleanField(default=False, verbose_name='На территории'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='last_entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего въезда'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='last_exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего выезда'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='status',
            field=models.CharField(choices=[('on_territory', 'На территории'), ('off_territory', 'Не на территории'), ('temporary', 'Временный доступ'), ('banned', 'Заблокирован')], default='off_territory', max_length=20, verbose_name='Статус доступа'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_access_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил'),
        ),
        migrations.AddIndex(
            model_name='accesslist',
            index=models.Index(fields=['status', 'date'], name='access_cont_status_e4ed96_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslist',
            index=models.Index(fields=['contractor', 'status'], name='access_cont_contrac_4b1212_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslist',
            index=models.Index(fields=['is_on_territory'], name='access_cont_is_on_t_f9a3b1_idx'),
        ),
    ]
