# Generated by Django 4.2.7 on 2026-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0010_accesslist_is_on_territory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Список доступа', 'verbose_name_plural': 'Списки доступа'},
        ),
        migrations.RemoveIndex(
            model_name='accesslist',
            name='access_cont_status_e4ed96_idx',
        ),
        migrations.AlterUniqueTogether(
            name='accesslist',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='accesslist',
            index=models.Index(fields=['status'], name='access_cont_status_66ef30_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslist',
            index=models.Index(fields=['valid_until'], name='access_cont_valid_u_d6d0da_idx'),
        ),
        migrations.RemoveField(
            model_name='accesslist',
            name='date',
        ),
    ]
